### ISSUE TITLE
Preceeding "doi:" is not accepted.

### ISSUE THREAD

**Issue by dennisguse** [davidagraf/doi2bib#17]
doi2bib does reject request as invalid, if a DOI has a preceding "doi:".

---
However, I often find DOIs online that formatted like this:

        doi:10.1016/0304-3959(96)02994-6

or even like this:

        http://dx.doi.org/10.1016/0304-3959(96)02994-6

This one is from ScienceDirect: http://www.sciencedirect.com/science/article/pii/0304395996029946

**Comment by davidagraf** [comment]
doi: prefix is supported since commit 44e99792e3ef5a9ea2968da7d4f2ace498db2b16.
