### ISSUE TITLE
problems with BSSA doi 

### ISSUE THREAD

**Issue by fiorellalan** [davidagraf/doi2bib#23]
With all papers published on BSSA (such as: http://www.bssaonline.org/content/95/2/745.short)
this issue is raised:  
 Parse error on line 1:
<!DOCTYPE html PUBLI...
^
Expecting '@', got 'TEXT'

**Comment by thurnherr** [comment]
Thanks for letting us know. This has been fixed and works now.
http://www.doi2bib.org/#/doi/10.1785/0120040160
