### ISSUE TITLE
[feature request] Create telegram bot

### ISSUE THREAD

**Issue by egorpugin** [davidagraf/doi2bib#25]
Hi there,

Is it possible to create a Telegram doi2bib bot?
Telegram is a messaging app.
https://telegram.org/
https://core.telegram.org/bots
https://core.telegram.org/bots/api

Workflow is very easy as is with your site. Send doi to bot - get bibtex record.

**Comment by shogane** [comment]
Hi,

My suggestion would be to directly query doi.org or crossref.org. You can find more information on the Crossref API [here](http://search.crossref.org/help/api).

**Comment by egorpugin** [comment]
I see. But they don't give bibtex via API. Or am I missing something?

**Comment by shogane** [comment]
They do, this is essentially how we obtain BibTeX entries. [Here's a python script](https://gist.github.com/jrsmith3/5513926) that does the same. Hope this helps.

**Comment by egorpugin** [comment]
Thanks a lot! So, closing this...
