### ISSUE TITLE
incorrect year for a DOI

### ISSUE THREAD

**Issue by mankoff** [davidagraf/doi2bib#27]
http://www.doi2bib.org/#/doi/10.1002/esp.3648

Is a 2015 paper, but reported here as 2014.

**Comment by thurnherr** [comment]
Thanks for the input. According to the website, the article was first published online in 2014, hence the year 2014. Even though the printed version of the article appeared in an issue of the journal in 2015. In general, we query these data through the DOI API and provide them without checking for inconsistencies. However, as the data is provided directly by the publisher, it is rather unlikely that it is inconsistent.
HTH.
