### ISSUE TITLE
https://doi.org/10.1007/978-3-642-24418-6_11 Not works

### ISSUE THREAD

**Issue by timofonic** [davidagraf/doi2bib#36]
Hello.

This one does not work in many places, despite it's valid.

https://doi.org/10.1007/978-3-642-24418-6_11
    Andrea Capiluppi, Cornelia Boldyreff, Klaas-Jan Stol. (2011) Successful Reuse of Software Components: A Report from the Open Source Perspective. In: Hissam S.A., Russo B., de Mendonça Neto M.G., Kon F. (eds) Open Source Systems: Grounding Research. OSS 2011. IFIP Advances in Information and Communication Technology, vol 365. Springer, Berlin, Heidelberg

DOI https://doi.org/10.1007/978-3-642-24418-6_11 
Publisher Name Springer, Berlin, Heidelberg 
Print ISBN 978-3-642-24417-9 
Online ISBN 978-3-642-24418-6

**Comment by thurnherr** [comment]
It seems that the problem is resolved now.

https://doi2bib.org/bib/10.1007%2F978-3-642-24418-6_11
