### ISSUE TITLE
doi2bib.org not working

### ISSUE THREAD

**Issue by Jellby** [davidagraf/doi2bib#37]
The site doi2bib.org is not working since a few days ago. Any connection with this repository (apart from the name and the code)?

**Comment by psavery** [comment]
I can confirm that it is still not working.

**Comment by austindowney** [comment]
Sadly, it is still not working.

**Comment by Jellby** [comment]
Seems to be working now.

**Comment by thurnherr** [comment]
We updated the code base and moved to another cloud service. Sorry for the inconvenience. The code is available [here now](https://github.com/davidagraf/doi2bib2).

**Comment by psavery** [comment]
Website appears to be down again.

**Comment by thurnherr** [comment]
We are working on a fix. In the meantime, try this link: https://www.doi2bib.org
